### ISSUE TITLE
Getting Media Player to work

### ISSUE THREAD

**Issue by MagnusHL** [cgarwood/homeassistant-fullykiosk#127]
Hi!

I have a fresh install and want to get the mediaplayer running, then a motion ist detected.
I am using an Amazon Fire HD 10

I am testing, but I cannot get anything to play.

```
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.fire_tablet
    data:
      media_content_type: music
      media_content_id: http://live-icy.gss.dr.dk/A/A12H.mp3
```

Nothing is happening AND no error message.
If I use service:media_player.media_play I get an error.

Any suggestions?
