### ISSUE TITLE
Add camera

### ISSUE THREAD

**Issue by SamMousa** [cgarwood/homeassistant-fullykiosk#35]
The FKB API exposes the camera, my config to load it looks like this:
```
camera:
  - platform: generic
    verify_ssl: false
    still_image_url: http://192.168.2.12:2323/?cmd=getCamshot&password=xxx
```

It would be nice if this integration could expose the camera.
