### ISSUE TITLE
Play Audio file

### ISSUE THREAD

**Issue by pickonedev** [cgarwood/homeassistant-fullykiosk#61]
Hi!

Anyone knows how to use the Play Media feature of this integration from Home Assistant?

If I put a file from Media folder, the tablet will try to connect to HA and play that file, but insteand of playing, I get ban for the tablet's IP

This is what I use

```
service: fullykiosk.play_audio
data:
  entity_id: media_player.computer_tablet_media_player
  stream: 3
  url: http://192.168.0.102:8123/media/local/trance.mp3
```

I found something on the internet but it is not a good solution. 
Adding "?authSig=********" at the end of the url
It is working till I restart HA, then the authSig is different...

PS: I don't use NodeRed

Thank you in advace
