### ISSUE TITLE
set_config motionDetection How to turn it off/on

### ISSUE THREAD

**Issue by pickonedev** [cgarwood/homeassistant-fullykiosk#62]
Hi!

Can anyone tell me how can I use set_config in HA to switch the motionDetection key state?

I tried this and I get error

```
service: fullykiosk.set_config
data:
  entity_id: media_player.computer_tablet_media_player
  key: 'motionDetection'
  value: 'off'
```
error
`Failed to call service fullykiosk.set_config. required key not provided @ data['config_type']. Got None`

Thank you in advance!

**Comment by pickonedev** [comment]
Solved!

```
service: fullykiosk.set_config
data:
  entity_id: media_player.computer_tablet_media_player
  config_type: bool
  key: motionDetection
  value: true
```
