### ISSUE TITLE
Error playing media on tablet

### ISSUE THREAD

**Issue by portigui** [cgarwood/homeassistant-fullykiosk#91]
Fire Tablet 8
Fully Kiosk Version: 1.46-fire
Home Assistant Version: 2022.3.3

I am attempting to play a wav file via the FK integration's media player. I am using the following script:
```
  arming_alarm_zones_closed:
    alias: Arming Alarm Zone Open
    sequence:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.porte_cochere_control_panel
        message: "Arming Alarm"
    - delay:
        seconds: 3
    - service: media_player.play_media
      data_template:
        entity_id: media_player.porte_cochere_control_panel
        media_content_id: /local/media/alarm-activating1.wav
        media_content_type: 'music'
```
The TTS service call that points to the media player works with no issue. Trying to pass in the media to play does not give an error in the HA logs however does give the following error displayed on the tablet screen:
```
Failed loading sound: Wrong URL or unsupported format?
```
If I change the media player entity to another one in my house with no other changes, that script works just fine.

Is there a different way that I am supposed to be playing media? Is there a specific format that is supported other than `wav`? I have tried converting the audio to `mp3` and changed the type to `audio/mp3` and although it works on the other media player, that also fails the same way on the tablet.

Any assistance would be appreciated.
